_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: L-22k
  FPN:
    IN_FEATURES: [ "swin0", "swin1", "swin2", "swin3" ]
  ROI_HEADS:
    NUM_CLASSES: 4  # 
  DiffusionDet:
    NUM_PROPOSALS: 1000
    NUM_CLASSES: [4,8,4]  # 
    USE_FED_LOSS: True  # 
DATASETS:  # 
  TRAIN: ("custom_train_class",)
  TEST: ("custom_validation_class",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 40000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:  # LVIS
  EVAL_PERIOD: 1000  # disable eval during train since long time